# Generated by Django 4.2.4 on 2023-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="audio_files/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.PositiveIntegerField()),
                ("file_extension", models.CharField(max_length=5)),
            ],
        ),
    ]
